### PR TITLE
Html and css

### PR DESCRIPTION
**Pull request by ohClaire**
Add icons to images folder.
Change color scheme.
Add classes to html tags.

### CODE REVIEW

**Review by coleanthony1990 — CHANGES_REQUESTED** [review]
Just need to add ids to manipulatable elements.

**Review by coleanthony1990 — APPROVED** [review]
all good here!

**Review by emilyjmiles — CHANGES_REQUESTED** [review]
Please change id's to camelCase. Otherwise it looks great!

**Review by emilyjmiles — APPROVED** [review]
Thank you for fixing those!

**Pull request merged**
